version: "3.9"

networks:
  build_default:
    name: build_default
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: go-invoice-grafana
    network_mode: "bridge"
    depends_on:
      - prometheus
      - prometheus-pushgateway
  
  prometheus:
    image: prom/prometheus
    ports:
      -9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    valumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: go-invoice-prometheus
    network_mode: "bridge"

  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: go-invoice-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
  